name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          cache: yarn
          cache-dependency-path: ./yarn.lock
          node-version: 24.14.0

      - run: yarn install --frozen-lockfile
      - run: yarn run prettier --check .
